import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Ferro's privacy policy.",
};

const EFFECTIVE_DATE = "August 24, 2026";

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" effectiveDate={EFFECTIVE_DATE}>
      <p>
        Ferro Fleet LLC (&quot;Ferro,&quot; &quot;we,&quot; &quot;us,&quot; or
        &quot;our&quot;) operates Ferro, a fleet management platform for
        exotic and luxury vehicle rental operators. This Privacy Policy
        explains what information we collect through the Service, how we use
        and share it, and the choices and rights available to you. It applies
        to our marketing site, the Ferro dashboard, and public storefronts
        hosted on Ferro. It should be read alongside our{" "}
        <a href="/terms">Terms of Service</a>.
      </p>
      <p>
        We are based in California, and this Policy is written with
        California&apos;s privacy law (the CCPA/CPRA) specifically in mind,
        in addition to general privacy practices we apply to all users.
      </p>

      <h2>1. Information We Collect</h2>
      <h3>Account &amp; Company Information</h3>
      <p>
        When you create an account or a Company workspace, we collect your
        name, email address, and role, and information about your Company
        (business name, storefront slug, and similar details).
      </p>
      <h3>Fleet &amp; Business Data</h3>
      <p>
        Vehicle details, availability, booking and customer contact
        information (name, email, phone), invoices, internal team messages,
        inquiries submitted through your storefront, and contracts you send
        for signature.
      </p>
      <h3>Sensitive Documents</h3>
      <p>
        If your Company uploads them, we store renter identification photos
        (e.g., driver&apos;s license images) and insurance declaration
        (&quot;dec&quot;) pages. These are stored separately from your public
        vehicle photos, in private, access-controlled storage that is not
        exposed on your public storefront.
      </p>
      <h3>GPS &amp; Location Data</h3>
      <p>
        If you connect a Bouncie GPS device to a vehicle, we retrieve and
        display that vehicle&apos;s location, speed, running status, trip
        history, fuel level, odometer, and diagnostic data from the Bouncie
        API. This data is generated by the device and Bouncie&apos;s
        service, not by Ferro directly.
      </p>
      <h3>Payment Information</h3>
      <p>
        Subscription billing and any invoicing your Company sends to its
        customers is processed through <strong>Stripe</strong>. We do not
        store full payment card numbers ourselves; Stripe collects and
        stores that information under its own privacy policy. We do receive
        limited data back from Stripe, such as payment status, invoice
        amounts, and identifiers needed to reconcile billing.
      </p>
      <h3>Usage &amp; Device Information</h3>
      <p>
        Like most web services, our infrastructure provider (Vercel) and
        authentication provider (Supabase) automatically log standard
        technical data such as IP address, browser type, device type, and
        request timestamps, for security, debugging, and abuse prevention.
        We use session cookies necessary for authentication and, where
        applicable, a cookie to remember your light/dark theme preference.
        We do not currently use third-party advertising trackers or
        cross-site analytics cookies on the Service.
      </p>

      <h2>2. How We Use Information</h2>
      <ul>
        <li>To provide, maintain, and secure the Service, including keeping each Company&apos;s data separated from other Companies&apos;;</li>
        <li>to process payments and subscription billing;</li>
        <li>to display GPS/location, trip, and diagnostic data for vehicles you&apos;ve connected;</li>
        <li>to send transactional email (e.g., invites, booking notifications, password resets) via Resend;</li>
        <li>to route contracts for e-signature via DocuSign or PandaDoc, as directed by you;</li>
        <li>to render maps via Google Maps where you&apos;ve enabled location display;</li>
        <li>to respond to support requests and enforce our Terms; and</li>
        <li>to comply with legal obligations.</li>
      </ul>

      <h2>3. How We Share Information</h2>
      <p>
        We do not sell your personal information. We share information with
        the following categories of third parties, only as needed to
        provide the Service:
      </p>
      <ul>
        <li><strong>Stripe</strong> — payment processing and billing.</li>
        <li><strong>Bouncie</strong> — GPS/telematics data for vehicles you connect a device to.</li>
        <li><strong>DocuSign / PandaDoc</strong> — whichever e-signature provider you connect, to send and manage contracts.</li>
        <li><strong>Google Maps</strong> — to render vehicle location pins when you view the Tracking page.</li>
        <li><strong>Resend</strong> — to deliver transactional email on our behalf.</li>
        <li><strong>Supabase</strong> — our database, authentication, and file storage infrastructure.</li>
        <li><strong>Vercel</strong> — our application hosting infrastructure.</li>
      </ul>
      <p>
        We may also disclose information if required by law, to protect the
        rights, property, or safety of Ferro, our users, or others, or in
        connection with a merger, acquisition, or sale of assets (with
        notice to affected users where required).
      </p>

      <h2>4. Multi-Tenant Data Separation</h2>
      <p>
        Ferro hosts many Companies on shared infrastructure. Each
        Company&apos;s data — including customer records, sensitive
        documents, and GPS data — is logically separated and
        access-controlled so only that Company&apos;s authorized users can
        access it. See Section 6 of our <a href="/terms">Terms of
        Service</a> for more detail.
      </p>

      <h2>5. Data Storage &amp; Security</h2>
      <p>
        Data is stored using Supabase (built on PostgreSQL) and object
        storage, hosted in the United States. We use access controls,
        encryption in transit, and role-based permissions to protect data.
        Identification documents and insurance dec pages are kept in private
        storage buckets that are never served publicly. No method of storage
        or transmission is 100% secure, and we cannot guarantee absolute
        security.
      </p>

      <h2>6. Data Retention</h2>
      <p>
        We retain your Company&apos;s data for as long as your account is
        active, and for a limited period afterward to allow for data export
        and to meet legal, accounting, or dispute-resolution needs. You can
        request deletion of your account and associated data at any time,
        subject to Section 7 below and any records we&apos;re required to
        keep by law (for example, payment records).
      </p>

      <h2>7. Your Privacy Rights</h2>
      <h3>California Residents (CCPA/CPRA)</h3>
      <p>If you are a California resident, you have the right to:</p>
      <ul>
        <li><strong>Know</strong> what personal information we collect, use, and disclose;</li>
        <li><strong>Delete</strong> personal information we&apos;ve collected, subject to certain exceptions;</li>
        <li><strong>Correct</strong> inaccurate personal information;</li>
        <li><strong>Opt out</strong> of the sale or sharing of personal information — we do not sell or share personal information for cross-context behavioral advertising; and</li>
        <li>not be discriminated against for exercising these rights.</li>
      </ul>
      <p>
        To exercise these rights, contact us at{" "}
        <a href="mailto:privacy@joinferro.com">privacy@joinferro.com</a>. We
        will verify your request and respond within the timeframes required
        by law.
      </p>
      <h3>All Users</h3>
      <p>
        Regardless of location, you can request access to, correction of, or
        deletion of your personal information by contacting us at the email
        above, or through your account settings where self-service tools are
        available. If you&apos;re an individual whose data was uploaded by a
        Company you rented from or work for (rather than a Ferro account
        holder yourself), please contact that Company directly, as they
        control that data; we will assist them in fulfilling valid requests.
      </p>

      <h2>8. Children&apos;s Privacy</h2>
      <p>
        The Service is intended for business use by adults and is not
        directed to children. We do not knowingly collect personal
        information from anyone under 18. If you believe a child has
        provided us with personal information, contact us and we will
        delete it.
      </p>

      <h2>9. International Users</h2>
      <p>
        The Service and our infrastructure are based in the United States.
        If you access Ferro from outside the United States, your information
        will be transferred to and processed in the United States.
      </p>

      <h2>10. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. If we make
        material changes, we will provide reasonable notice (such as an
        in-app notice or email) before the changes take effect.
      </p>

      <h2>11. Contact Us</h2>
      <p>
        Questions or requests regarding this Privacy Policy or your data can
        be sent to{" "}
        <a href="mailto:privacy@joinferro.com">privacy@joinferro.com</a>.
      </p>
    </LegalPage>
  );
}
